version: "3.8"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - backend
    restart: unless-stopped

volumes:
  .venv:

networks:
  backend:
    driver: bridge
