version: "3.8"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8111:8111"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - backend # This specifies that the container joins the 'backend' network
    restart: unless-stopped

volumes:
  .venv:

networks:
  backend:
    driver:
      bridge # This creates a network named 'backend' using the bridge driver
      # The bridge driver is the default network driver in Docker
      # It creates an isolated network on the host where containers can communicate
      # with each other but are isolated from the host network by default
      # This is useful for container-to-container communication while maintaining security
